# Generated by Django 5.0 on 2026-03-30 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0029_add_match_maps_to_tournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text email body. You can include links by pasting full URLs.')),
                ('recipient_type', models.CharField(choices=[('all_users', 'All Users (Players + Hosts)'), ('all_players', 'All Players'), ('all_hosts', 'All Hosts'), ('tournament_participants', 'Tournament Participants'), ('individual_users', 'Individual Users')], default='all_players', max_length=30)),
                ('tournament_status_filter', models.CharField(choices=[('all', 'All Tournaments'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing (Live)'), ('completed', 'Completed')], default='all', help_text="Only used when recipient type is 'Tournament Participants'. Filter which tournaments to include when no specific tournaments are selected.", max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_sent', models.IntegerField(default=0, help_text='Number of emails successfully sent.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if sending failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('selected_tournaments', models.ManyToManyField(blank=True, help_text='Select specific tournaments. Leave empty to target ALL tournaments (filtered by tournament status filter below).', to='tournaments.tournament')),
                ('selected_users', models.ManyToManyField(blank=True, help_text='Select specific users to send this email to.', related_name='broadcast_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Email',
                'verbose_name_plural': 'Broadcast Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
