# Generated by Django 5.0 on 2026-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_add_issue_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
