# Generated by Django 5.0 on 2026-01-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0014_aadharverification"),
        ("tournaments", "0017_alter_hostrating_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "merchant_order_id",
                    models.CharField(help_text="Unique order ID generated by us", max_length=100, unique=True),
                ),
                (
                    "phonepe_order_id",
                    models.CharField(blank=True, help_text="Order ID generated by PhonePe", max_length=100),
                ),
                (
                    "phonepe_transaction_id",
                    models.CharField(blank=True, help_text="Transaction ID from PhonePe", max_length=100),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("tournament_plan", "Tournament Plan"),
                            ("scrim_plan", "Scrim Plan"),
                            ("entry_fee", "Entry Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, help_text="Amount in INR", max_digits=10)),
                ("amount_paisa", models.IntegerField(help_text="Amount in paisa (for PhonePe API)")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_mode", models.CharField(blank=True, help_text="UPI, Card, NetBanking, etc.", max_length=50)),
                (
                    "instrument_type",
                    models.CharField(blank=True, help_text="ACCOUNT, CREDIT_CARD, DEBIT_CARD, etc.", max_length=50),
                ),
                ("redirect_url", models.URLField(blank=True, help_text="PhonePe checkout URL")),
                (
                    "callback_data",
                    models.JSONField(blank=True, default=dict, help_text="Complete callback response from PhonePe"),
                ),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("detailed_error_code", models.CharField(blank=True, max_length=100)),
                ("meta_info", models.JSONField(blank=True, default=dict, help_text="Additional metadata (udf1-5)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="accounts.hostprofile",
                    ),
                ),
                (
                    "player_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="accounts.playerprofile",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="tournaments.tournamentregistration",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "merchant_refund_id",
                    models.CharField(help_text="Unique refund ID generated by us", max_length=100, unique=True),
                ),
                (
                    "phonepe_refund_id",
                    models.CharField(blank=True, help_text="Refund ID generated by PhonePe", max_length=100),
                ),
                ("amount", models.DecimalField(decimal_places=2, help_text="Refund amount in INR", max_digits=10)),
                ("amount_paisa", models.IntegerField(help_text="Refund amount in paisa")),
                ("reason", models.TextField(blank=True, help_text="Reason for refund")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "callback_data",
                    models.JSONField(blank=True, default=dict, help_text="Complete callback response from PhonePe"),
                ),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("detailed_error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="payments.payment"
                    ),
                ),
            ],
            options={
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["merchant_order_id"], name="payments_pa_merchan_b6aa47_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["phonepe_order_id"], name="payments_pa_phonepe_1dba7e_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "payment_type"], name="payments_pa_user_id_e74e24_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["merchant_refund_id"], name="payments_re_merchan_6780a6_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["phonepe_refund_id"], name="payments_re_phonepe_1b7c5b_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status"], name="payments_re_status_715c3a_idx"),
        ),
    ]
