# Generated by Django 5.0 on 2026-01-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="detailed_error_code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="redirect_url",
            field=models.TextField(blank=True, help_text="PhonePe checkout URL"),
        ),
        migrations.AlterField(
            model_name="refund",
            name="phonepe_refund_id",
            field=models.CharField(blank=True, help_text="Refund ID generated by PhonePe", max_length=255),
        ),
    ]
