# Generated by Django 5.0 on 2026-01-23 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_payment_options_alter_refund_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_merchan_b6aa47_idx",
            old_name="payments_merchan_c6b9a5_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_phonepe_1dba7e_idx",
            old_name="payments_phonepe_311df9_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_status_7ad4af_idx",
            old_name="payments_status_d621e5_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_user_id_e74e24_idx",
            old_name="payments_user_id_de337b_idx",
        ),
        migrations.RenameIndex(
            model_name="refund",
            new_name="payments_re_merchan_6780a6_idx",
            old_name="refunds_merchan_8206e1_idx",
        ),
        migrations.RenameIndex(
            model_name="refund",
            new_name="payments_re_phonepe_1b7c5b_idx",
            old_name="refunds_phonepe_0b5bc8_idx",
        ),
        migrations.RenameIndex(
            model_name="refund",
            new_name="payments_re_status_715c3a_idx",
            old_name="refunds_status_2569d8_idx",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payments_payment",
        ),
        migrations.AlterModelTable(
            name="refund",
            table="payments_refund",
        ),
    ]
