# Generated by Django 5.0 on 2026-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_payment_detailed_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_expires_at",
            field=models.DateTimeField(blank=True, help_text="Payment expiry time (12 hours from creation)", null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="pending_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Temporary storage for tournament/registration data until payment is completed",
            ),
        ),
    ]
