# Generated by Django 5.0 on 2026-01-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_remove_pending_payment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPricing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("tournament_basic", "Tournament - Basic"),
                            ("tournament_featured", "Tournament - Featured"),
                            ("tournament_premium", "Tournament - Premium"),
                            ("scrim_basic", "Scrim - Basic"),
                            ("scrim_featured", "Scrim - Featured"),
                            ("scrim_premium", "Scrim - Premium"),
                        ],
                        db_index=True,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in INR (set to 0 for free plans)", max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Enable/disable this plan")),
                ("description", models.TextField(blank=True, help_text="Internal notes about this pricing")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plan Pricing",
                "verbose_name_plural": "Plan Pricing",
                "ordering": ["plan_type"],
            },
        ),
    ]
