# Generated by Django - Manual data migration

from decimal import Decimal

from django.db import migrations


def seed_plan_pricing(apps, schema_editor):
    """Seed initial plan pricing data"""
    PlanPricing = apps.get_model("payments", "PlanPricing")

    # Default pricing
    pricing_data = [
        {
            "plan_type": "tournament_basic",
            "price": Decimal("299.00"),
            "is_active": True,
            "description": "Basic tournament plan with essential features",
        },
        {
            "plan_type": "tournament_featured",
            "price": Decimal("499.00"),
            "is_active": True,
            "description": "Featured tournament plan with enhanced visibility",
        },
        {
            "plan_type": "tournament_premium",
            "price": Decimal("799.00"),
            "is_active": True,
            "description": "Premium tournament plan with all features",
        },
        {
            "plan_type": "scrim_basic",
            "price": Decimal("299.00"),
            "is_active": True,
            "description": "Basic scrim plan with essential features",
        },
        {
            "plan_type": "scrim_featured",
            "price": Decimal("499.00"),
            "is_active": True,
            "description": "Featured scrim plan with enhanced visibility",
        },
        {
            "plan_type": "scrim_premium",
            "price": Decimal("699.00"),
            "is_active": True,
            "description": "Premium scrim plan with all features",
        },
    ]

    for pricing in pricing_data:
        PlanPricing.objects.get_or_create(
            plan_type=pricing["plan_type"],
            defaults={
                "price": pricing["price"],
                "is_active": pricing["is_active"],
                "description": pricing["description"],
            },
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded data"""
    PlanPricing = apps.get_model("payments", "PlanPricing")
    PlanPricing.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_planpricing"),
    ]

    operations = [
        migrations.RunPython(seed_plan_pricing, reverse_seed),
    ]
