from django.db import models
from django.utils import timezone

from accounts.models import HostProfile, PlayerProfile
from tournaments.models import Tournament, TournamentRegistration


class Payment(models.Model):
    """
    Model to track all payment transactions
    """

    PAYMENT_TYPE_CHOICES = (
        ("tournament_plan", "Tournament Plan"),
        ("scrim_plan", "Scrim Plan"),
        ("entry_fee", "Entry Fee"),
    )

    PAYMENT_STATUS_CHOICES = (
        ("pending", "Pending"),
        ("completed", "Completed"),
        ("failed", "Failed"),
    )

    # Payment Identification
    merchant_order_id = models.CharField(max_length=100, unique=True, help_text="Unique order ID generated by us")
    phonepe_order_id = models.CharField(max_length=100, blank=True, help_text="Order ID generated by PhonePe")
    phonepe_transaction_id = models.CharField(max_length=100, blank=True, help_text="Transaction ID from PhonePe")

    # Payment Details
    payment_type = models.CharField(max_length=20, choices=PAYMENT_TYPE_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=2, help_text="Amount in INR")
    amount_paisa = models.IntegerField(help_text="Amount in paisa (for PhonePe API)")

    # User Information
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE, related_name="payments")
    player_profile = models.ForeignKey(
        PlayerProfile, on_delete=models.SET_NULL, null=True, blank=True, related_name="payments"
    )
    host_profile = models.ForeignKey(
        HostProfile, on_delete=models.SET_NULL, null=True, blank=True, related_name="payments"
    )

    # Related Objects
    tournament = models.ForeignKey(
        Tournament, on_delete=models.SET_NULL, null=True, blank=True, related_name="payments"
    )
    registration = models.ForeignKey(
        TournamentRegistration, on_delete=models.SET_NULL, null=True, blank=True, related_name="payments"
    )

    # Payment Status
    status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default="pending")
    payment_mode = models.CharField(max_length=50, blank=True, help_text="UPI, Card, NetBanking, etc.")
    instrument_type = models.CharField(max_length=50, blank=True, help_text="ACCOUNT, CREDIT_CARD, DEBIT_CARD, etc.")

    # PhonePe Response Data
    redirect_url = models.URLField(blank=True, help_text="PhonePe checkout URL")
    callback_data = models.JSONField(default=dict, blank=True, help_text="Complete callback response from PhonePe")
    error_code = models.CharField(max_length=50, blank=True)
    detailed_error_code = models.CharField(max_length=100, blank=True)

    # Metadata
    meta_info = models.JSONField(default=dict, blank=True, help_text="Additional metadata (udf1-5)")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.merchant_order_id} - {self.payment_type} - ₹{self.amount}"

    def save(self, *args, **kwargs):
        # Auto-calculate amount in paisa
        if self.amount:
            self.amount_paisa = int(self.amount * 100)

        # Set completed_at when status changes to completed
        if self.status == "completed" and not self.completed_at:
            self.completed_at = timezone.now()

        super().save(*args, **kwargs)

    class Meta:
        db_table = "payments_payment"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["merchant_order_id"]),
            models.Index(fields=["phonepe_order_id"]),
            models.Index(fields=["status"]),
            models.Index(fields=["user", "payment_type"]),
        ]


class Refund(models.Model):
    """
    Model to track refund transactions
    """

    REFUND_STATUS_CHOICES = (
        ("pending", "Pending"),
        ("accepted", "Accepted"),
        ("completed", "Completed"),
        ("failed", "Failed"),
    )

    # Refund Identification
    merchant_refund_id = models.CharField(max_length=100, unique=True, help_text="Unique refund ID generated by us")
    phonepe_refund_id = models.CharField(max_length=100, blank=True, help_text="Refund ID generated by PhonePe")

    # Related Payment
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, related_name="refunds")

    # Refund Details
    amount = models.DecimalField(max_digits=10, decimal_places=2, help_text="Refund amount in INR")
    amount_paisa = models.IntegerField(help_text="Refund amount in paisa")
    reason = models.TextField(blank=True, help_text="Reason for refund")

    # Refund Status
    status = models.CharField(max_length=20, choices=REFUND_STATUS_CHOICES, default="pending")

    # PhonePe Response Data
    callback_data = models.JSONField(default=dict, blank=True, help_text="Complete callback response from PhonePe")
    error_code = models.CharField(max_length=50, blank=True)
    detailed_error_code = models.CharField(max_length=100, blank=True)

    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Refund {self.merchant_refund_id} - ₹{self.amount}"

    def save(self, *args, **kwargs):
        # Auto-calculate amount in paisa
        if self.amount:
            self.amount_paisa = int(self.amount * 100)

        # Set completed_at when status changes to completed
        if self.status == "completed" and not self.completed_at:
            self.completed_at = timezone.now()

        super().save(*args, **kwargs)

    class Meta:
        db_table = "payments_refund"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["merchant_refund_id"]),
            models.Index(fields=["phonepe_refund_id"]),
            models.Index(fields=["status"]),
        ]
