# Generated by Django 5.0 on 2025-11-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("game_name", models.CharField(max_length=100)),
                ("game_mode", models.CharField(max_length=100)),
                ("max_participants", models.IntegerField()),
                ("current_participants", models.IntegerField(default=0)),
                ("entry_fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("scrim_start", models.DateTimeField()),
                ("scrim_end", models.DateTimeField()),
                ("rules", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("banner_image", models.ImageField(blank=True, null=True, upload_to="scrims/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scrims", to="accounts.hostprofile"
                    ),
                ),
            ],
            options={
                "db_table": "scrims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("game_name", models.CharField(max_length=100)),
                ("game_mode", models.CharField(max_length=100)),
                ("max_participants", models.IntegerField()),
                ("current_participants", models.IntegerField(default=0)),
                ("entry_fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("prize_pool", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prize_distribution", models.JSONField(default=dict)),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("tournament_start", models.DateTimeField()),
                ("tournament_end", models.DateTimeField()),
                ("rules", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("banner_image", models.ImageField(blank=True, null=True, upload_to="tournaments/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="accounts.hostprofile",
                    ),
                ),
            ],
            options={
                "db_table": "tournaments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField()),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="accounts.hostprofile"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_ratings",
                        to="accounts.playerprofile",
                    ),
                ),
                (
                    "scrim",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tournaments.scrim"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
                    ),
                ),
            ],
            options={
                "db_table": "host_ratings",
            },
        ),
        migrations.CreateModel(
            name="ScrimRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_name", models.CharField(blank=True, max_length=100)),
                ("team_members", models.JSONField(blank=True, default=list)),
                ("in_game_details", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                ("payment_id", models.CharField(blank=True, max_length=100)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrim_registrations",
                        to="accounts.playerprofile",
                    ),
                ),
                (
                    "scrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tournaments.scrim",
                    ),
                ),
            ],
            options={
                "db_table": "scrim_registrations",
                "ordering": ["-registered_at"],
                "unique_together": {("scrim", "player")},
            },
        ),
        migrations.CreateModel(
            name="TournamentRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_name", models.CharField(blank=True, max_length=100)),
                ("team_members", models.JSONField(blank=True, default=list)),
                ("in_game_details", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                ("payment_id", models.CharField(blank=True, max_length=100)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_registrations",
                        to="accounts.playerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_registrations",
                "ordering": ["-registered_at"],
                "unique_together": {("tournament", "player")},
            },
        ),
    ]
