# Generated by Django 5.0 on 2025-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_tournament_discord_id_tournament_rounds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.IntegerField(default=0, help_text="Current active round (0 = not started)"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="round_status",
            field=models.JSONField(
                blank=True, default=dict, help_text="Round status: {'1': 'completed', '2': 'ongoing', '3': 'upcoming'}"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="selected_teams",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Selected teams per round: {'1': [reg_id1, reg_id2], '2': [reg_id3, reg_id4]}",
            ),
        ),
    ]
