# Generated by Django 5.0 on 2025-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_tournament_current_round_tournament_round_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winners",
            field=models.JSONField(
                blank=True, default=dict, help_text="Winners per round: {'2': reg_id1} (final round winner)"
            ),
        ),
    ]
