# Generated by Django 5.0 on 2025-11-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_tournament_winners"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.IntegerField()),
                ("position_points", models.IntegerField(default=0)),
                ("kill_points", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_scores",
                        to="tournaments.tournamentregistration",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_scores",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "round_scores",
                "unique_together": {("tournament", "round_number", "team")},
            },
        ),
    ]
