# Generated by Django 5.0 on 2026-01-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0011_group_qualifying_teams_group_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="event_mode",
            field=models.CharField(
                choices=[("TOURNAMENT", "Tournament"), ("SCRIM", "Scrim")],
                default="TOURNAMENT",
                help_text="Event type: Tournament (competitive) or Scrim (practice)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_matches",
            field=models.IntegerField(
                default=6, help_text="Maximum number of matches (for scrims, max 6; for tournaments, based on rounds)"
            ),
        ),
    ]
