# Generated by Django 5.0 on 2026-01-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0012_tournament_event_mode_tournament_max_matches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="prize_pool",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
