# Generated by Django 5.0 on 2026-01-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0013_alter_tournament_prize_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="game_name",
            field=models.CharField(
                choices=[("BGMI", "BGMI"), ("COD", "COD Mobile"), ("Freefire", "Free Fire"), ("Scarfall", "Scarfall")],
                max_length=100,
            ),
        ),
    ]
