# Generated by Django 5.0 on 2026-01-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0014_alter_tournament_game_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="game_name",
            field=models.CharField(
                choices=[
                    ("BGMI", "BGMI"),
                    ("COD", "Call of Duty"),
                    ("Freefire", "Free Fire"),
                    ("Scarfall", "Scarfall"),
                ],
                max_length=100,
            ),
        ),
    ]
