# Generated by Django 5.0 on 2026-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0015_alter_tournament_game_name"),
    ]

    operations = [
        # First, remove the unique_together constraint (before removing fields it references)
        migrations.AlterUniqueTogether(
            name="scrimregistration",
            unique_together=set(),
        ),
        # Then remove the fields
        migrations.RemoveField(
            model_name="scrimregistration",
            name="scrim",
        ),
        migrations.RemoveField(
            model_name="hostrating",
            name="scrim",
        ),
        migrations.RemoveField(
            model_name="scrimregistration",
            name="player",
        ),
        migrations.RemoveField(
            model_name="scrimregistration",
            name="team",
        ),
        # Finally, delete the models
        migrations.DeleteModel(
            name="Scrim",
        ),
        migrations.DeleteModel(
            name="ScrimRegistration",
        ),
    ]
