# Generated by Django 5.0 on 2026-01-15 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0016_remove_scrim_models_and_unused_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hostrating",
            options={"ordering": ["-created_at"]},
        ),
    ]
