# Generated by Django 5.0 on 2026-01-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0017_alter_hostrating_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="round_names",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom names for rounds: {'1': 'Qualifiers', '2': 'Semi Finals', '3': 'Grand Finals'}",
            ),
        ),
    ]
