# Generated by Django 5.0 on 2026-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0017_alter_hostrating_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_payment_pending",
            field=models.BooleanField(default=False, help_text="True if tournament is created but payment is pending"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="payment_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for completing payment (12 hours from creation)", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="is_payment_pending",
            field=models.BooleanField(
                default=False, help_text="True if registration is created but payment is pending"
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="payment_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for completing payment (12 hours from registration)", null=True
            ),
        ),
    ]
