# Generated by Django 5.0 on 2026-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0019_remove_payment_pending_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Listing"),
                    ("featured", "Featured Listing"),
                    ("premium", "Premium + Promotion"),
                ],
                default="basic",
                help_text="Tournament plan type",
                max_length=20,
            ),
        ),
    ]
