# Generated by Django 5.0 on 2026-01-25 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0018_add_round_names"),
        ("tournaments", "0020_alter_tournament_plan_type"),
    ]

    operations = []
