# Generated by Django 5.0 on 2026-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0021_merge_20260125_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="map_name",
            field=models.CharField(
                blank=True, help_text="Game map name for this match (e.g., Erangel, Miramar)", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="scheduled_date",
            field=models.DateField(blank=True, help_text="Scheduled date for this match", null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="scheduled_time",
            field=models.TimeField(blank=True, help_text="Scheduled time for this match", null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="placement_points",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Placement points mapping: {rank: points}. Example: {'1': 15, '2': 12, '3': 10}",
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="invited_members_status",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Status of invited members: {email: {status: 'pending'|'accepted'|'declined'|'expired', username: str|null}}",
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="is_team_created",
            field=models.BooleanField(
                default=False, help_text="Track if real Team object has been created after payment"
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="temp_teammate_emails",
            field=models.JSONField(
                blank=True, default=list, help_text="Temporary storage of invited teammate emails before payment"
            ),
        ),
    ]
