# Generated by Django 5.0 on 2026-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_match_map_name_match_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('Squad', 'Squad'), ('Duo', 'Duo'), ('Solo', 'Solo'), ('5v5', '5v5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_name',
            field=models.CharField(choices=[('BGMI', 'BGMI'), ('COD', 'Call of Duty'), ('Valorant', 'Valorant'), ('Freefire', 'Free Fire'), ('Scarfall', 'Scarfall')], max_length=100),
        ),
    ]
