# Generated by Django 5.0 on 2026-02-11 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_alter_tournament_game_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning team for this group (5v5 tournaments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_groups', to='tournaments.tournamentregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning team for this match (5v5 tournaments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.tournamentregistration'),
        ),
    ]
