# Generated by Django 5.0 on 2026-02-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_group_winner_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning team for 5v5 format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_groups', to='tournaments.tournamentregistration'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning team for 5v5 format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.tournamentregistration'),
        ),
    ]
