# Generated by Django 5.0 on 2026-03-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_tournament_round_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='credential_release_time',
            field=models.DateTimeField(blank=True, help_text='When room ID & password become visible to registered players', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='slot_list_release_time',
            field=models.DateTimeField(blank=True, help_text='When slot list becomes visible to registered players', null=True),
        ),
    ]
