# Generated by Django 5.0 on 2026-03-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_add_credential_slot_release_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_maps',
            field=models.JSONField(blank=True, default=dict, help_text="Map selections per match index, e.g. {1: 'Erangel', 2: 'Miramar'}"),
        ),
    ]
