# Generated by Django 5.0 on 2026-05-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_add_match_maps_to_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sponsor_type', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('website_url', models.URLField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_sponsors',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
