# Generated by Django 5.0 on 2026-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_add_tournament_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='coupon_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='special_awards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
