# Generated by Django 5.0 on 2026-06-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_add_special_awards_coupon_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='ign_locked',
            field=models.BooleanField(default=False, help_text='Whether the IGN has been submitted and locked for this registration'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='ign_submissions',
            field=models.JSONField(blank=True, default=dict, help_text='Per-player IGN for this tournament. {username: ign, ...}'),
        ),
    ]
