# Generated by Django 5.0 on 2026-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_add_ign_fields_to_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='credential_release_time',
            field=models.DateTimeField(blank=True, help_text="When this match's room ID/password become visible to players. Null = reveal immediately.", null=True),
        ),
    ]
