# Generated by Django 5.0 on 2026-06-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_add_team_member_temp_fields'),
        ('tournaments', '0033_match_credential_release_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tournament', 'status'], name='reg_tournament_status_idx'),
        ),
    ]
