# Generated by Django 5.0 on 2026-05-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField(blank=True, default='', help_text='WhatsApp community invite link')),
                ('instagram_link', models.URLField(blank=True, default='', help_text='Instagram profile or community link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Settings',
                'verbose_name_plural': 'Community Settings',
            },
        ),
        migrations.CreateModel(
            name='CommunityJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_joins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Join',
                'verbose_name_plural': 'Community Joins',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'community_type')},
            },
        ),
    ]
