# Generated by Django 5.0 on 2025-11-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostprofile",
            name="organization_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=1234567899, max_length=10),
            preserve_default=False,
        ),
    ]
