# Generated by Django 5.0 on 2026-01-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_teamstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstatistics",
            name="scrim_kill_points",
            field=models.IntegerField(default=0, help_text="Kill points from scrims only"),
        ),
        migrations.AddField(
            model_name="teamstatistics",
            name="scrim_position_points",
            field=models.IntegerField(default=0, help_text="Position points from scrims only"),
        ),
        migrations.AddField(
            model_name="teamstatistics",
            name="scrim_wins",
            field=models.IntegerField(default=0, help_text="Number of scrim victories (1st place finishes)"),
        ),
        migrations.AddField(
            model_name="teamstatistics",
            name="tournament_kill_points",
            field=models.IntegerField(default=0, help_text="Kill points from tournaments only"),
        ),
        migrations.AddField(
            model_name="teamstatistics",
            name="tournament_position_points",
            field=models.IntegerField(default=0, help_text="Position points from tournaments only"),
        ),
    ]
