# Generated by Django 5.0 on 2026-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_teamstatistics_scrim_kill_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstatistics",
            name="scrim_rank",
            field=models.IntegerField(default=0, help_text="Scrim leaderboard rank"),
        ),
        migrations.AddField(
            model_name="teamstatistics",
            name="tournament_rank",
            field=models.IntegerField(default=0, help_text="Tournament leaderboard rank"),
        ),
        migrations.AlterField(
            model_name="teamstatistics",
            name="rank",
            field=models.IntegerField(default=0, help_text="Total (overall) leaderboard rank"),
        ),
    ]
