# Generated by Django 5.0 on 2026-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_teamstatistics_scrim_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, default="WE ARE BEAST", help_text="Team tagline or description"),
        ),
        migrations.AddField(
            model_name="team",
            name="profile_picture",
            field=models.ImageField(blank=True, help_text="Team logo/profile picture", null=True, upload_to="teams/"),
        ),
    ]
