# Generated by Django 5.0 on 2026-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_team_description_team_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamjoinrequest",
            name="request_type",
            field=models.CharField(
                choices=[("request", "Request"), ("invite", "Invite")], default="request", max_length=20
            ),
        ),
    ]
