# Generated by Django 5.0 on 2026-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_teamjoinrequest_request_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostprofile",
            name="social_links",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="skill_level",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="wallet_balance",
        ),
    ]
