# Generated by Django 5.0 on 2026-01-15 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_hostprofile_aadhar_card_back_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AadharVerification",
            fields=[],
            options={
                "verbose_name": "Aadhar Verification",
                "verbose_name_plural": "Aadhar Verifications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.hostprofile",),
        ),
    ]
