# Generated by Django 5.0 on 2026-02-08 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_add_password_reset_fields"),
        ("tournaments", "0022_match_map_name_match_scheduled_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamjoinrequest",
            name="invite_expires_at",
            field=models.DateTimeField(blank=True, help_text="Expiration time for the invite", null=True),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="invite_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique token for email-based invites",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="invited_email",
            field=models.EmailField(
                blank=True, help_text="Email address of the invited player", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="tournament_registration",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the tournament registration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="tournaments.tournamentregistration",
            ),
        ),
        migrations.AlterField(
            model_name="teamjoinrequest",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teamjoinrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
