# Generated by Django 5.0 on 2026-02-11 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_teamjoinrequest_invite_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstatistics',
            options={'ordering': ['-total_points'], 'verbose_name_plural': 'Team Statistics'},
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='game_name',
            field=models.CharField(choices=[('BGMI', 'BGMI'), ('COD', 'Call of Duty'), ('Valorant', 'Valorant'), ('Freefire', 'Free Fire'), ('Scarfall', 'Scarfall'), ('ALL', 'All Games')], default='ALL', help_text="Game-specific stats. 'ALL' represents aggregate stats across all games.", max_length=100),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_by_game', to='accounts.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamstatistics',
            unique_together={('team', 'game_name')},
        ),
    ]
