# Generated by Django 5.0 on 2026-02-11 05:35

from django.db import migrations


def set_all_game_name(apps, schema_editor):
    """
    Set game_name to 'ALL' for any existing TeamStatistics records
    that don't have a game_name set (NULL or empty).
    This ensures all pre-existing stats are treated as aggregate stats.
    """
    TeamStatistics = apps.get_model('accounts', 'TeamStatistics')
    
    # Update any records where game_name is NULL or empty
    updated = TeamStatistics.objects.filter(
        game_name__isnull=True
    ).update(game_name='ALL')
    
    # Also ensure default value for any empty strings
    updated += TeamStatistics.objects.filter(
        game_name=''
    ).update(game_name='ALL')
    
    if updated > 0:
        print(f"Updated {updated} TeamStatistics records to game_name='ALL'")
    else:
        print("No TeamStatistics records needed updating (all already have game_name set)")


def reverse_migration(apps, schema_editor):
    """Reverse operation (no-op since we can't unset game_name safely)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_teamstatistics_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_all_game_name, reverse_migration),
    ]
