# Generated by Django 5.0 on 2026-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_set_existing_stats_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='game_id',
            field=models.CharField(blank=True, help_text="Player's unique game ID/UID", max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='in_game_name',
            field=models.CharField(blank=True, help_text="Player's in-game character name", max_length=100),
        ),
    ]
