# Generated by Django 5.0 on 2026-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_playerprofile_game_id_playerprofile_in_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='game_id',
            field=models.CharField(blank=True, default='', help_text="Player's game ID or UID", max_length=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='in_game_name',
            field=models.CharField(blank=True, default='', help_text="Player's in-game name", max_length=100),
        ),
    ]
