# Generated by Django 5.0 on 2026-03-15 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('team_invite', 'Team Invite'), ('match_start', 'Match Starting Soon'), ('credential_release', 'Credentials Released'), ('slot_list', 'Slot List Published'), ('results', 'Results Published'), ('teammate_joined', 'Teammate Joined'), ('tournament_update', 'Tournament Update'), ('registration_confirmed', 'Registration Confirmed'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
