# Generated by Django 5.0 on 2026-03-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamjoinrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.CharField(blank=True, choices=[('BGMI', 'BGMI'), ('Valorant', 'Valorant'), ('Free Fire', 'Free Fire'), ('COD Mobile', 'COD Mobile'), ('Scarfall', 'Scarfall')], help_text='Primary game for this team', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamjoinrequest',
            name='invite_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('username', 'Username')], help_text='How the invite was sent', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamjoinrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS invites', max_length=20, null=True),
        ),
    ]
