# Generated by Django 5.0 on 2026-03-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_teamjoinrequest_unique_together_team_game_and_more'),
        ('tournaments', '0028_add_credential_slot_release_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conversion_deadline',
            field=models.DateTimeField(blank=True, help_text='48h window for captain to keep this temp team permanently', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linked_tournament',
            field=models.ForeignKey(blank=True, help_text='Tournament this temp team was created for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_teams', to='tournaments.tournament'),
        ),
    ]
