# Generated by Django 5.0 on 2026-03-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_team_linked_tournament_conversion_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatistics',
            name='matches_played',
            field=models.IntegerField(default=0, help_text='Total individual matches played (tournaments + scrims)'),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='scrim_matches_played',
            field=models.IntegerField(default=0, help_text='Number of individual scrim matches played'),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='tournament_matches_played',
            field=models.IntegerField(default=0, help_text='Number of individual tournament matches played'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('team_invite', 'Team Invite'), ('match_start', 'Match Starting Soon'), ('credential_release', 'Credentials Released'), ('slot_list', 'Slot List Published'), ('results', 'Results Published'), ('teammate_joined', 'Teammate Joined'), ('tournament_update', 'Tournament Update'), ('registration_confirmed', 'Registration Confirmed'), ('general', 'General'), ('team_conversion_offer', 'Team Conversion Offer')], default='general', max_length=30),
        ),
    ]
