# Generated by Django 5.0 on 2026-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_matches_played_to_teamstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='game_profiles',
            field=models.JSONField(blank=True, default=dict, help_text='Per-game IGN and Game ID. Format: {"BGMI": {"ign": "...", "game_id": "..."}, "Valorant": {...}, ...}. Supported keys: BGMI, Valorant, COD, Freefire, Scarfall.'),
        ),
    ]
