# Generated by Django 5.0 on 2026-03-16 09:13

from django.db import migrations


def migrate_ign_forward(apps, schema_editor):
    PlayerProfile = apps.get_model('accounts', 'PlayerProfile')
    for profile in PlayerProfile.objects.all():
        if profile.in_game_name and not profile.game_profiles.get('BGMI'):
            profile.game_profiles['BGMI'] = {
                'ign': profile.in_game_name,
                'game_id': profile.game_id or '',
            }
            profile.save(update_fields=['game_profiles'])


def migrate_ign_backward(apps, schema_editor):
    pass  # No rollback needed — old fields still exist


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_add_game_profiles_to_playerprofile'),
    ]

    operations = [
        migrations.RunPython(migrate_ign_forward, migrate_ign_backward),
    ]
