# Generated by Django 5.0 on 2026-03-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_migrate_ign_to_game_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number is verified via OTP'),
        ),
    ]
