# Generated by Django 5.0 on 2026-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_add_role_to_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Player notification preferences: {enableNotifications, matchReminders, tournamentUpdates, teamInvites, marketingEmails}'),
        ),
        migrations.AlterField(
            model_name='teamjoinrequest',
            name='invite_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('username', 'Username'), ('link', 'Link')], help_text='How the invite was sent', max_length=20, null=True),
        ),
    ]
