# Generated by Django 5.0 on 2026-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_increase_phone_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social links: {"instagram": "...", "youtube": "...", "discord": "..."}'),
        ),
    ]
