# Generated by Django 5.0 on 2026-03-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_notification_preferences_to_hostprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('team_invite', 'Team Invite'), ('match_start', 'Match Starting Soon'), ('credential_release', 'Credentials Released'), ('slot_list', 'Slot List Published'), ('results', 'Results Published'), ('teammate_joined', 'Teammate Joined'), ('tournament_update', 'Tournament Update'), ('registration_confirmed', 'Registration Confirmed'), ('general', 'General'), ('team_conversion_offer', 'Team Conversion Offer'), ('team_conversion_reminder', 'Team Conversion Reminder'), ('team_deleted', 'Team Deleted'), ('payment_confirmed', 'Payment Confirmed'), ('points_entered', 'Match Points Entered'), ('tournament_result', 'Tournament Result'), ('slot_list_release', 'Slot List Released'), ('new_registration', 'New Team Registration'), ('slots_full', 'Tournament Slots Full'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('tournament_start_reminder', 'Tournament Starting Soon'), ('payment_received', 'Payment Received')], default='general', max_length=50),
        ),
    ]
