# Generated by Django 5.0 on 2026-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_add_payout_details_to_hostprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_verify_redirect',
            field=models.CharField(blank=True, help_text='URL to redirect to after email verification', max_length=500, null=True),
        ),
    ]
