# Generated by Django 5.0 on 2026-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_add_post_verify_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='conversion_deadline',
            field=models.DateTimeField(blank=True, help_text='48h window for this member to keep this team permanently (only set when is_temporary=True)', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='True if this membership is temporary for the current user — set when they joined this team while already having a permanent team for the same game. They get the convert/decline prompt.'),
        ),
    ]
